#!/bin/bash
#PBS -l nodes=1:ppn=2 -l mem=6gb
#PBS -l walltime=00:30:00
#PBS -j oe
#PBS -N mamin-ift6266
#-q soumet
#PBS -r n
#-m ba
#-M masseeh.amin@gmail.com
#PBS -V
# --------------------------------------------------------------
module add python/3.5.1
module add CUDA/7.5
module add openblas/0.2.18

cd /home2/ift6ed05/code

source nn-project-p3.5/bin/activate

THEANO_FLAGS='device=gpu,floatX=float32' python ift6266/code/learn.py